# Generated by Django 5.1.5 on 2025-01-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_category_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_url',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
