# Generated by Django 5.1.5 on 2025-01-26 18:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cartinfo_orders_info_order_items_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('shipping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.BigIntegerField()),
                ('shipping_address', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('estimated_delivery_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.orders_info')),
            ],
            options={
                'db_table': 'Shipping_info',
            },
        ),
    ]
